// Esegui questo script UNA VOLTA sul server per inizializzare menu.json
// node init-menu.js

const fs = require('fs')
const path = require('path')

const menu = {
  antipasti: [
    { id: 'ant-1', price: 14, frozen: false, available: true, allergens: ['crustacean','molluscs','celery'], name: { it: 'Insalata di Mare', fr: 'Salade de Mer', de: 'Meeresfrüchtesalat', en: 'Seafood Salad', es: 'Ensalada de Mar' }, desc: { it: 'Tris di Polpo, Calamaro e Gambero, con pomodoro ciliegina di stagione e sedano croccante', fr: 'Trio de Poulpe, Calmar et Crevette, avec tomates cerises de saison et céleri croquant', de: 'Trio aus Oktopus, Kalmar und Garnele, mit Kirschtomaten und Sellerie', en: 'Trio of Octopus, Squid and Prawn, with cherry tomatoes and crunchy celery', es: 'Trío de Pulpo, Calamar y Gamba, con tomates cherry y apio crujiente' } },
    { id: 'ant-2', price: 15, frozen: false, available: true, allergens: ['fish','sulphites'], name: { it: 'Tonno Rosso alla Calasettana', fr: 'Thon Rouge à la Calasettana', de: 'Roter Thunfisch auf Calasettaner Art', en: 'Bluefin Tuna Calasettana Style', es: 'Atún Rojo a la Calasettana' }, desc: { it: 'Tonno con cipolla rossa in agrodolce e pomodoro fresco di stagione', fr: 'Thon avec oignon rouge aigre-doux et tomate fraîche', de: 'Thunfisch mit süß-saurer roter Zwiebel und frischen Tomaten', en: 'Bluefin tuna with sweet and sour red onion and fresh seasonal tomatoes', es: 'Atún con cebolla roja en agridulce y tomate fresco de temporada' } },
    { id: 'ant-3', price: 14, frozen: false, available: true, allergens: ['gluten','molluscs'], name: { it: 'Cozze in Salsa di Pangrattato', fr: 'Moules en Sauce à la Chapelure', de: 'Muscheln in Semmelbröselsauce', en: 'Mussels in Breadcrumb Sauce', es: 'Mejillones en Salsa de Pan Rallado' }, desc: { it: 'Cozze di Sardegna con pangrattato, pepe nero e pomodoro fresco di stagione', fr: 'Moules de Sardaigne avec chapelure, poivre noir et tomate fraîche', de: 'Sardische Muscheln mit Semmelbrösel, Pfeffer und Tomaten', en: 'Sardinian mussels with breadcrumbs, black pepper and fresh tomatoes', es: 'Mejillones de Cerdeña con pan rallado, pimienta negra y tomate fresco' } },
    { id: 'ant-4', price: 14, frozen: false, available: true, allergens: ['molluscs','celery'], name: { it: 'Insalata di Polpo', fr: 'Salade de Poulpe', de: 'Oktopussalat', en: 'Octopus Salad', es: 'Ensalada de Pulpo' }, desc: { it: 'Polpo in insalata con sedano croccante', fr: 'Poulpe en salade avec céleri croquant', de: 'Oktopussalat mit knackigem Sellerie', en: 'Octopus salad with crunchy celery', es: 'Pulpo en ensalada con apio crujiente' } },
    { id: 'ant-5', price: 17, frozen: false, available: true, allergens: ['molluscs','sulphites'], name: { it: 'Sauté di Cozze e Vongole Piccante', fr: 'Sauté de Moules et Palourdes Épicé', de: 'Scharfer Muscheln-Sauté', en: 'Spicy Mussels and Clams Sauté', es: 'Salteado Picante de Mejillones y Almejas' }, desc: { it: 'Cozze e Vongole di Sardegna in salsa piccante con pomodoro fresco di stagione', fr: 'Moules et Palourdes en sauce épicée avec tomate fraîche', de: 'Sardische Muscheln in scharfer Sauce mit Tomaten', en: 'Sardinian mussels and clams in spicy sauce with fresh tomatoes', es: 'Mejillones y almejas en salsa picante con tomate fresco' } },
    { id: 'ant-6', price: 13, frozen: true, available: true, allergens: ['gluten','fish'], name: { it: 'Frittura di Anemoni di Mare', fr: "Friture d'Anémones de Mer", de: 'Frittierte Seeanemonen', en: 'Fried Sea Anemones', es: 'Fritura de Anémonas de Mar' }, desc: { it: 'Frittura di Anemoni servite in cono di Carasau', fr: "Friture d'Anémones dans un cône de pain Carasau", de: 'Frittierte Seeanemonen im Carasau-Kegel', en: 'Fried sea anemones served in a Carasau bread cone', es: 'Fritura de anémonas en cono de pan Carasau' } },
    { id: 'ant-7', price: 15, frozen: false, available: true, allergens: ['gluten','fish'], name: { it: 'Capunadda', fr: 'Capunadda', de: 'Capunadda', en: 'Capunadda', es: 'Capunadda' }, desc: { it: 'Tonno stagionato sotto sale con facussa croccante, galletta Tabarchina e pomodoro fresco', fr: 'Thon séché avec courgette croquante, galette Tabarchine et tomate fraîche', de: 'Gereifter Thunfisch mit Facussa, Tabarchina-Cracker und Tomaten', en: 'Salt-cured tuna with crunchy facussa, Tabarchina cracker and fresh tomatoes', es: 'Atún curado con facussa crujiente, galleta Tabarchina y tomate fresco' } },
  ],
  pasta: [
    { id: 'pas-1', price: 17, frozen: true, available: true, allergens: ['gluten','crustacean','molluscs','eggs'], name: { it: 'Culurgiones al Nero di Seppia', fr: "Culurgiones à l'Encre de Seiche", de: 'Culurgiones mit Tintenfischtinte', en: 'Culurgiones in Cuttlefish Ink', es: 'Culurgiones al Nero di Seppia' }, desc: { it: 'Culurgiones neri ripieni di Gamberi, Vongole e Cozze con pomodoro ciliegino saltato', fr: 'Culurgiones noirs farcis de Crevettes, Palourdes et Moules avec tomates cerises', de: 'Schwarze Culurgiones mit Garnelen, Venusmuscheln und Muscheln', en: 'Black Culurgiones filled with Prawns, Clams and Mussels with sautéed cherry tomatoes', es: 'Culurgiones negros rellenos de Gambas, Almejas y Mejillones con tomates cherry' } },
    { id: 'pas-2', price: 19, frozen: true, available: true, allergens: ['gluten','fish','molluscs'], name: { it: 'Spaghetti al Riccio di Mare', fr: "Spaghetti à l'Oursin", de: 'Spaghetti mit Seeigel', en: 'Spaghetti with Sea Urchin', es: 'Spaghetti al Erizo de Mar' }, desc: { it: 'Spaghetti mantecati alla polpa di Riccio — Pasta di Gragnano IGP 100% grano Italiano', fr: "Spaghetti mantecati à la pulpe d'Oursin — Pâtes de Gragnano IGP", de: 'Spaghetti mit Seeigelfleisch — Gragnano IGP Pasta', en: 'Spaghetti mantecati with Sea Urchin pulp — Gragnano IGP Pasta', es: 'Spaghetti con pulpa de Erizo — Pasta de Gragnano IGP' } },
    { id: 'pas-3', price: 20, frozen: false, available: true, allergens: ['gluten','fish','molluscs','sulphites'], name: { it: 'Linguine al Sapore di Mare', fr: 'Linguine au Goût de Mer', de: 'Linguine mit Meeresgeschmack', en: 'Linguine with Sea Flavours', es: 'Linguine al Sabor de Mar' }, desc: { it: 'Linguine con Vongole di Sardegna, Bottarga e polpa di Riccio — Pasta di Gragnano IGP', fr: "Linguine aux Palourdes, Bottarga et Oursin — Pâtes de Gragnano IGP", de: 'Linguine mit Venusmuscheln, Bottarga und Seeigel — Gragnano IGP', en: 'Linguine with Clams, Bottarga and Sea Urchin — Gragnano IGP Pasta', es: 'Linguine con Almejas, Bottarga y Erizo — Pasta de Gragnano IGP' } },
    { id: 'pas-4', price: 20, frozen: true, available: true, allergens: ['gluten','crustacean','sulphites'], name: { it: 'Spaghetti al Gambero Rosso', fr: 'Spaghetti à la Crevette Rouge', de: 'Spaghetti mit Roter Garnele', en: 'Spaghetti with Red Prawn', es: 'Spaghetti a la Gamba Roja' }, desc: { it: 'Spaghetti, bisque di Gambero rosso e salsa di pomodoro — Pasta di Gragnano IGP', fr: 'Spaghetti, bisque de Crevette rouge et sauce tomate — Gragnano IGP', de: 'Spaghetti, Bisque von roter Garnele und Tomatensauce — Gragnano IGP', en: 'Spaghetti with red prawn bisque and tomato sauce — Gragnano IGP Pasta', es: 'Spaghetti con bisque de Gamba roja y salsa de tomate — Gragnano IGP' } },
    { id: 'pas-5', price: 17, frozen: true, available: true, allergens: ['gluten','fish','sulphites'], name: { it: 'Trofie Artigianali alla Cernia', fr: 'Trofie Artisanales au Mérou', de: 'Handgemachte Trofie mit Zackenbarsch', en: 'Artisanal Trofie with Grouper', es: 'Trofie Artesanales con Mero' }, desc: { it: 'Con polpa di cernia, Bottarga, concassé di zucchine — Truffiette di Carloforte (Pastificio Luxoro)', fr: 'Avec pulpe de Mérou, Bottarga, courgettes — Truffiette de Carloforte', de: 'Mit Zackenbarsch, Bottarga, Zucchini — Truffiette aus Carloforte', en: 'With grouper, Bottarga, courgette concassé — Truffiette from Carloforte', es: 'Con Mero, Bottarga, calabacín — Truffiette de Carloforte' } },
    { id: 'pas-6', price: 17, frozen: false, available: true, allergens: ['gluten','molluscs'], name: { it: 'Paccheri Napoletani alle Cozze', fr: 'Paccheri Napolitains aux Moules', de: 'Neapolitanische Paccheri mit Muscheln', en: 'Neapolitan Paccheri with Mussels', es: 'Paccheri Napolitanos con Mejillones' }, desc: { it: 'Paccheri mantecati alla crema di zucchine con sauté di cozze di Sardegna — Pasta di Gragnano IGP', fr: 'Paccheri à la crème de courgettes avec moules de Sardaigne — Gragnano IGP', de: 'Paccheri mit Zucchini-Creme und sardischen Muscheln — Gragnano IGP', en: 'Paccheri with courgette cream and sautéed Sardinian mussels — Gragnano IGP', es: 'Paccheri con crema de calabacín y mejillones de Cerdeña — Gragnano IGP' } },
    { id: 'pas-7', price: 18, frozen: true, available: true, allergens: ['gluten','crustacean','molluscs'], name: { it: 'Fregola alla Marinara', fr: 'Fregola à la Marinara', de: 'Fregola alla Marinara', en: 'Fregola alla Marinara', es: 'Fregola a la Marinara' }, desc: { it: 'Fregola con Gamberi, Calamari, Vongole, Cozze, Scampi e salsa di pomodoro — Pasta di Sardegna', fr: 'Fregola avec Crevettes, Calamars, Palourdes, Moules, Langoustines — Pâtes de Sardaigne', de: 'Fregola mit Garnelen, Kalmaren, Muscheln und Kaisergranaten — Sardische Pasta', en: 'Fregola with Prawns, Squid, Clams, Mussels, Scampi — Sardinian Pasta', es: 'Fregola con Gambas, Calamares, Almejas, Mejillones, Langostinos — Pasta de Cerdeña' } },
  ],
  secondi: [
    { id: 'sec-1', price: 7, frozen: false, available: true, priceNote: { it: '/ hg', fr: '/ 100g', de: '/ 100g', en: '/ 100g', es: '/ 100g' }, allergens: ['fish','sulphites'], name: { it: 'Pesce Fresco di Giornata', fr: 'Poisson Frais du Jour', de: 'Tagesfrischer Fisch', en: 'Fresh Catch of the Day', es: 'Pescado Fresco del Día' }, desc: { it: 'In base al pescato — alla griglia con salamoia o Vermentino di Sardegna e aromi mediterranei', fr: 'Selon la pêche — grillé avec saumure ou Vermentino de Sardaigne', de: 'Je nach Fang — gegrillt mit Salzlake oder Vermentino', en: "According to the catch — grilled with brine or Sardinian Vermentino", es: 'Según la pesca — a la parrilla con salmuera o Vermentino' } },
    { id: 'sec-2', price: 18, frozen: true, available: true, allergens: ['fish'], name: { it: 'Tonno Rosso del Mediterraneo', fr: 'Thon Rouge de Méditerranée', de: 'Roter Thunfisch aus dem Mittelmeer', en: 'Mediterranean Bluefin Tuna', es: 'Atún Rojo del Mediterráneo' }, desc: { it: 'Pregiato Tonno rosso alla griglia con salamoia e concassé di pomodori aromatici', fr: 'Thon rouge grillé avec saumure et concassé de tomates', de: 'Gegrillter Roter Thunfisch mit Salzlake und Tomaten-Concassé', en: 'Grilled Bluefin Tuna with brine and aromatic tomato concassé', es: 'Atún Rojo a la parrilla con salmuera y concassé de tomates' } },
    { id: 'sec-3', price: 16, frozen: true, available: true, allergens: ['fish'], name: { it: 'Pesce Spada', fr: 'Espadon', de: 'Schwertfisch', en: 'Swordfish', es: 'Pez Espada' }, desc: { it: 'Pescespada mediterraneo alla griglia con salamoia e concassé di pomodori aromatici', fr: 'Espadon grillé avec saumure et concassé de tomates', de: 'Gegrillter Schwertfisch mit Salzlake und Tomaten-Concassé', en: 'Mediterranean swordfish grilled with brine and tomato concassé', es: 'Pez Espada a la parrilla con salmuera y concassé de tomates' } },
    { id: 'sec-4', price: 15, frozen: true, available: true, allergens: ['molluscs'], name: { it: 'Seppie alla Griglia', fr: 'Seiches Grillées', de: 'Gegrillte Tintenfische', en: 'Grilled Cuttlefish', es: 'Sepias a la Parrilla' }, desc: { it: 'Servite con salamoia e concassé di pomodori aromatici', fr: 'Servies avec saumure et concassé de tomates', de: 'Serviert mit Salzlake und Tomaten-Concassé', en: 'Served with brine and aromatic tomato concassé', es: 'Servidas con salmuera y concassé de tomates' } },
    { id: 'sec-5', price: 18, frozen: true, available: true, allergens: ['gluten','molluscs','eggs'], name: { it: 'Calamari Fritti', fr: 'Calamars Frits', de: 'Frittierte Kalmari', en: 'Fried Squid', es: 'Calamares Fritos' }, desc: { it: 'Frittura di Calamari con maionese di mare profumata al lime', fr: 'Friture de Calamars avec mayonnaise de mer au citron vert', de: 'Frittierte Kalmari mit Limetten-Meeresmayonnaise', en: 'Fried squid with lime-infused seafood mayonnaise', es: 'Fritura de Calamares con mayonesa de mar con lima' } },
    { id: 'sec-6', price: 19, frozen: true, available: true, allergens: ['gluten','crustacean','molluscs','eggs'], name: { it: 'Frittura Mista', fr: 'Friture Mixte', de: 'Gemischte Frittierung', en: 'Mixed Fried Seafood', es: 'Fritura Mixta' }, desc: { it: 'Frittura di Calamari e Gamberi con maionese di mare profumata al lime', fr: 'Friture de Calamars et Crevettes avec mayonnaise au citron vert', de: 'Kalmari und Garnelen mit Limetten-Meeresmayonnaise', en: 'Fried squid and prawns with lime-infused seafood mayonnaise', es: 'Fritura de Calamares y Gambas con mayonesa de mar con lima' } },
    { id: 'sec-7', price: 17, frozen: true, available: true, allergens: ['crustacean','sulphites'], name: { it: 'Gamberoni Argentini al Vermentino', fr: 'Gambas Argentines au Vermentino', de: 'Argentinische Garnelen mit Vermentino', en: 'Argentine Prawns with Vermentino', es: 'Gambones Argentinos al Vermentino' }, desc: { it: 'Cucinati al Vermentino con aromi mediterranei', fr: 'Cuisinés au Vermentino avec des arômes méditerranéens', de: 'Mit Vermentino und mediterranen Kräutern', en: 'Cooked with Vermentino wine and Mediterranean aromas', es: 'Cocinados al Vermentino con aromas mediterráneos' } },
    { id: 'sec-8', price: 6, frozen: true, available: true, priceNote: { it: '/ pz.', fr: '/ pièce', de: '/ Stück', en: '/ piece', es: '/ pieza' }, allergens: ['crustacean'], name: { it: 'Gamberoni Rossi alla Griglia', fr: 'Gambas Rouges Grillées', de: 'Gegrillte Rote Garnelen', en: 'Grilled Red Prawns', es: 'Gambones Rojos a la Parrilla' }, desc: { it: 'Serviti con salamoia', fr: 'Servis avec saumure', de: 'Mit Salzlake', en: 'Served with brine', es: 'Servidos con salmuera' } },
  ],
  contorni: [
    { id: 'con-1', price: 4, frozen: false, available: true, allergens: ['celery'], name: { it: 'Insalata Mista', fr: 'Salade Mixte', de: 'Gemischter Salat', en: 'Mixed Salad', es: 'Ensalada Mixta' }, desc: { it: 'Lattuga o Iceberg, Radicchio, Pomodoro, Carota', fr: 'Laitue ou Iceberg, Radicchio, Tomate, Carotte', de: 'Salat, Radicchio, Tomate, Karotte', en: 'Lettuce or Iceberg, Radicchio, Tomato, Carrot', es: 'Lechuga, Radicchio, Tomate, Zanahoria' } },
    { id: 'con-2', price: 3, frozen: false, available: true, allergens: [], name: { it: 'Insalata Verde', fr: 'Salade Verte', de: 'Grüner Salat', en: 'Green Salad', es: 'Ensalada Verde' }, desc: { it: 'Lattuga o Iceberg', fr: 'Laitue ou Iceberg', de: 'Kopfsalat oder Eisbergsalat', en: 'Lettuce or Iceberg', es: 'Lechuga o Iceberg' } },
    { id: 'con-3', price: 3, frozen: false, available: true, allergens: [], name: { it: 'Insalata di Pomodori', fr: 'Salade de Tomates', de: 'Tomatensalat', en: 'Tomato Salad', es: 'Ensalada de Tomates' }, desc: { it: 'Pomodoro insalataro', fr: 'Tomate à salade', de: 'Salattomaten', en: 'Salad tomatoes', es: 'Tomate ensaladero' } },
    { id: 'con-4', price: 10, frozen: false, available: true, allergens: ['milk','nuts'], name: { it: 'Selezione di Formaggi Locali', fr: 'Sélection de Fromages Locaux', de: 'Auswahl lokaler Käse', en: 'Selection of Local Cheeses', es: 'Selección de Quesos Locales' }, desc: { it: 'Serviti con miele millefiori, confettura di pere e di arance', fr: "Servis avec miel, confiture de poires et d'oranges", de: 'Mit Honig, Birnen- und Orangenkonfitüre', en: 'Served with wildflower honey, pear and orange jam', es: 'Con miel, mermelada de pera y naranja' } },
  ],
  dessert: [
    { id: 'des-1', price: 6, frozen: false, available: true, allergens: ['gluten','eggs','milk','nuts'], name: { it: 'Cheesecake al Caramello Salato', fr: 'Cheesecake au Caramel Salé', de: 'Cheesecake mit Salzkaramell', en: 'Salted Caramel Cheesecake', es: 'Cheesecake de Caramelo Salado' }, desc: { it: 'Servita con granella di nocciole', fr: 'Servie avec éclats de noisettes', de: 'Mit Haselnusssplittern', en: 'Served with chopped hazelnuts', es: 'Servida con granillo de avellanas' } },
    { id: 'des-2', price: 6, frozen: false, available: true, allergens: ['gluten','eggs','milk'], name: { it: 'Cheesecake ai Frutti di Bosco', fr: 'Cheesecake aux Fruits des Bois', de: 'Cheesecake mit Waldfrüchten', en: 'Wild Berry Cheesecake', es: 'Cheesecake de Frutos del Bosque' }, desc: { it: 'Servita con salsa ai frutti di bosco', fr: 'Servie avec sauce aux fruits des bois', de: 'Mit Waldfrüchtsauce', en: 'Served with wild berry sauce', es: 'Con salsa de frutos del bosque' } },
    { id: 'des-3', price: 7, frozen: false, available: true, allergens: ['gluten','eggs','milk'], name: { it: 'Tortino al Cioccolato con Cuore Fondente', fr: 'Moelleux au Chocolat', de: 'Schokoladenkuchen mit flüssigem Kern', en: 'Chocolate Fondant Cake', es: 'Coulant de Chocolate' }, desc: { it: 'Servito con gelato alla panna', fr: 'Servi avec glace à la crème', de: 'Mit Rahm-Eis', en: 'Served with cream ice cream', es: 'Con helado de nata' } },
    { id: 'des-4', price: 6, frozen: false, available: true, allergens: ['gluten','eggs','milk'], name: { it: 'Tiramisù', fr: 'Tiramisù', de: 'Tiramisù', en: 'Tiramisù', es: 'Tiramisù' }, desc: { it: 'Ricetta classica della casa', fr: 'Recette classique de la maison', de: 'Klassisches Hausrezept', en: 'Classic house recipe', es: 'Receta clásica de la casa' } },
    { id: 'des-5', price: 6, frozen: true, available: true, allergens: ['gluten','eggs','milk'], name: { it: 'Seadas', fr: 'Seadas', de: 'Seadas', en: 'Seadas', es: 'Seadas' }, desc: { it: 'Con formaggio fresco vaccino, servita con miele o zucchero', fr: 'Avec fromage frais, servies avec miel ou sucre', de: 'Mit frischem Käse, mit Honig oder Zucker', en: "With fresh cow's cheese, served with honey or sugar", es: 'Con queso fresco, servidas con miel o azúcar' } },
    { id: 'des-6', price: 7, frozen: true, available: true, allergens: ['gluten','eggs','milk'], name: { it: 'Seadas Nera', fr: 'Seadas Noire', de: 'Schwarze Seadas', en: 'Black Seadas', es: 'Seadas Negra' }, desc: { it: 'Al carbone vegetale con formaggio vaccino e caprino, servita con miele o zucchero', fr: 'Au charbon végétal avec fromages, servies avec miel ou sucre', de: 'Mit pflanzlicher Kohle und Käse, mit Honig oder Zucker', en: "With vegetable charcoal, cow's and goat's cheese, honey or sugar", es: 'Con carbón vegetal y quesos, con miel o azúcar' } },
    { id: 'des-7', price: 6, frozen: true, available: true, allergens: ['gluten','eggs','milk'], name: { it: 'Raviolini di Ricotta e Limone', fr: 'Raviolini à la Ricotta et Citron', de: 'Raviolini mit Ricotta und Zitrone', en: 'Raviolini with Ricotta and Lemon', es: 'Raviolini de Ricota y Limón' }, desc: { it: 'Di Ricotta dolce e scorza di limone, serviti con zucchero a velo', fr: 'De Ricotta douce et zeste de citron, avec sucre glace', de: 'Mit süßer Ricotta und Zitronenschale, mit Puderzucker', en: 'Sweet Ricotta and lemon zest, served with icing sugar', es: 'De Ricota dulce y ralladura de limón, con azúcar glas' } },
    { id: 'des-8', price: 4, frozen: false, available: true, allergens: [], name: { it: 'Sorbetto al Limone', fr: 'Sorbet au Citron', de: 'Zitronensorbet', en: 'Lemon Sorbet', es: 'Sorbete de Limón' }, desc: { it: '', fr: '', de: '', en: '', es: '' } },
  ],
  bibite: [
    { id: 'bib-1',  price: 2.50, frozen: false, available: true, allergens: [], name: { it: 'Acqua naturale / frizzante', fr: 'Eau naturelle / gazeuse', de: 'Stilles / Sprudelwasser', en: 'Still / Sparkling Water', es: 'Agua natural / con gas' }, desc: { it: '', fr: '', de: '', en: '', es: '' } },
    { id: 'bib-2',  price: 2.50, frozen: false, available: true, allergens: [], name: { it: 'Bibite in lattina 33 cl', fr: 'Boissons en canette 33 cl', de: 'Softdrinks Dose 33 cl', en: 'Soft Drinks can 33 cl', es: 'Refrescos en lata 33 cl' }, desc: { it: '', fr: '', de: '', en: '', es: '' } },
    { id: 'bib-3',  price: 2.50, frozen: false, available: true, allergens: ['gluten'], name: { it: 'Ichnusa 33 cl', fr: 'Ichnusa 33 cl', de: 'Ichnusa 33 cl', en: 'Ichnusa 33 cl', es: 'Ichnusa 33 cl' }, desc: { it: '', fr: '', de: '', en: '', es: '' } },
    { id: 'bib-4',  price: 4.50, frozen: false, available: true, allergens: ['gluten'], name: { it: 'Ichnusa 66 cl', fr: 'Ichnusa 66 cl', de: 'Ichnusa 66 cl', en: 'Ichnusa 66 cl', es: 'Ichnusa 66 cl' }, desc: { it: '', fr: '', de: '', en: '', es: '' } },
    { id: 'bib-5',  price: 3.50, frozen: false, available: true, allergens: ['gluten'], name: { it: 'Ichnusa Non Filtrata 33 cl', fr: 'Ichnusa Non Filtrée 33 cl', de: 'Ichnusa Ungefiltert 33 cl', en: 'Ichnusa Unfiltered 33 cl', es: 'Ichnusa Sin Filtrar 33 cl' }, desc: { it: '', fr: '', de: '', en: '', es: '' } },
    { id: 'bib-6',  price: 5.00, frozen: false, available: true, allergens: ['gluten'], name: { it: 'Ichnusa Non Filtrata 50 cl', fr: 'Ichnusa Non Filtrée 50 cl', de: 'Ichnusa Ungefiltert 50 cl', en: 'Ichnusa Unfiltered 50 cl', es: 'Ichnusa Sin Filtrar 50 cl' }, desc: { it: '', fr: '', de: '', en: '', es: '' } },
    { id: 'bib-7',  price: 5.00, frozen: false, available: true, allergens: ['gluten'], name: { it: 'Ichnusa Ambra Limpida 45 cl', fr: 'Ichnusa Ambra Limpida 45 cl', de: 'Ichnusa Ambra Limpida 45 cl', en: 'Ichnusa Ambra Limpida 45 cl', es: 'Ichnusa Ambra Limpida 45 cl' }, desc: { it: '', fr: '', de: '', en: '', es: '' } },
    { id: 'bib-8',  price: 3.00, frozen: false, available: true, allergens: ['gluten'], name: { it: 'Peroni Nastro Azzurro', fr: 'Peroni Nastro Azzurro', de: 'Peroni Nastro Azzurro', en: 'Peroni Nastro Azzurro', es: 'Peroni Nastro Azzurro' }, desc: { it: '', fr: '', de: '', en: '', es: '' } },
    { id: 'bib-9',  price: 9.00, frozen: false, available: true, allergens: ['gluten'], name: { it: 'Birre Artigianali 50 cl', fr: 'Bières Artisanales 50 cl', de: 'Craft Beer 50 cl', en: 'Craft Beers 50 cl', es: 'Cervezas Artesanales 50 cl' }, desc: { it: '', fr: '', de: '', en: '', es: '' } },
    { id: 'bib-10', price: 1.50, frozen: false, available: true, allergens: [], name: { it: 'Caffè', fr: 'Café', de: 'Espresso', en: 'Espresso', es: 'Café' }, desc: { it: '', fr: '', de: '', en: '', es: '' } },
    { id: 'bib-11', price: 2.00, frozen: false, available: true, allergens: ['milk'], name: { it: 'Caffè americano / corretto', fr: 'Caffè americano / corretto', de: 'Americano / Corretto', en: 'Americano / Corretto', es: 'Café americano / corretto' }, desc: { it: '', fr: '', de: '', en: '', es: '' } },
    { id: 'bib-12', price: 2.50, frozen: false, available: true, allergens: ['milk'], name: { it: 'Cappuccino', fr: 'Cappuccino', de: 'Cappuccino', en: 'Cappuccino', es: 'Cappuccino' }, desc: { it: '', fr: '', de: '', en: '', es: '' } },
    { id: 'bib-13', price: 3.50, frozen: false, available: true, allergens: ['sulphites'], name: { it: 'Amari / Liquori', fr: 'Amers / Liqueurs', de: 'Bitterliköre / Liköre', en: 'Bitters / Liqueurs', es: 'Amaros / Licores' }, desc: { it: '', fr: '', de: '', en: '', es: '' } },
    { id: 'bib-14', price: 5.00, frozen: false, available: true, allergens: [], name: { it: 'Grappa bianca', fr: 'Grappa blanche', de: 'Weißer Grappa', en: 'White Grappa', es: 'Grappa blanca' }, desc: { it: '', fr: '', de: '', en: '', es: '' } },
    { id: 'bib-15', price: 6.00, frozen: false, available: true, allergens: [], name: { it: 'Grappa barricata', fr: 'Grappa barriquée', de: 'Barrique-Grappa', en: 'Barrel-aged Grappa', es: 'Grappa barricada' }, desc: { it: '', fr: '', de: '', en: '', es: '' } },
    { id: 'bib-16', price: 7.00, frozen: false, available: true, allergens: [], name: { it: 'Abbardente', fr: 'Abbardente', de: 'Abbardente', en: 'Abbardente', es: 'Abbardente' }, desc: { it: 'Acquavite tradizionale sarda', fr: 'Eau-de-vie traditionnelle sarde', de: 'Traditioneller sardischer Obstbrand', en: 'Traditional Sardinian spirit', es: 'Aguardiente tradicional sardo' } },
    { id: 'bib-17', price: 7.00, frozen: false, available: true, allergens: [], name: { it: 'Whisky', fr: 'Whisky', de: 'Whisky', en: 'Whisky', es: 'Whisky' }, desc: { it: '', fr: '', de: '', en: '', es: '' } },
    { id: 'bib-18', price: 7.00, frozen: false, available: true, allergens: [], name: { it: 'Rum', fr: 'Rhum', de: 'Rum', en: 'Rum', es: 'Ron' }, desc: { it: '', fr: '', de: '', en: '', es: '' } },
  ],
}

const outputPath = path.join(__dirname, 'menu.json')
fs.writeFileSync(outputPath, JSON.stringify(menu, null, 2))
console.log(`menu.json creato con successo in ${outputPath}`)
